apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-test
  name: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
        labels:
          app: app-test
        annotations:
          feature-foo: "off"
          feature-bar: "on"
    spec:
      containers:
      - image: alvarocortes/acortes:1.0.0
        imagePullPolicy: Always
        name: app-test
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
        env:
        - name: ANNOTATIONS_PATH
          value: /etc/podinfo/annotations
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
