apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDln2wij5YtTb22RXe/2wsixtDL41OezNsQf5ow19iImH1Y+kZvbz6eLvc1DBVh1D+w+a2Upd18xJSyTbxfv06D4RZRXWPhYT+d/HE/N7Loc1cX4zf/KfAyHeq2G1KaPAOTQrFig4NYDu/t4dBj9DaPhqhq0HU5AE28PKhS16TbzcbbozCM56d37Em//gnctIFZVfR9AJCJJl3fVQuOHRnZmXSBMRzBqnviCQKNFfDVC3PH2OE19p5G592QJ2W+WwwZzXz5N+mKqzhPJ/A0G4HI1C7CZLcbJQP4lzWzoBYUuVVnMnkmrbTPrYIjV+P43ZOEGfnnO99IDcxIw+uIVkj2oZ34fVC2jenoYmFUTX3KITjYQSFn+L0LxPpXsq1KqE37yAzYuT6Eme1wMhGzYu3INHpd840R6zmTCS5wzpZVm1OO0M7atwx6SEtYitP09wmnhceY4cZVWCCNupZ1E233+jcPZOC0GFoMI7pauLasj36OmCs2Ti3/x0zZ5YU70zmKsRMhFHviM9OBfComjhkaZJSQcsz9Atj/eG0n4vG2+ww+WaQhhZl5Qj9bg7wV2kJsDdIKswKyuyeODPBOqCwSynMjFrDubTCjGFmC9tOPl5Ysp5FBfgb8LSWg11G7h1jog0E3WkwP7z8ddN6CM4QpD7iegFBDkqbKHSDtXLWTvMVlMi5E+GGaa2M41eYXz6KuYLU7oCVj8NjbqNVJaP1HwYCtztFcWl92C4BXVb+8APQZN4MSepwm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

