apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgB9qObS0i4Qax1Fe6AUF8Tlg9tuBgrVivxNYYSEg1c4B/zv0WAIQZMkIEG00P94sGORxg2azenRo9qP2uSbQQpQTgpXcHoytMKTqCF3zHx/FZVreQMSfEMXIe5GizBppjEpjqy804sCdDzzMkrkZZZwk+A8iSrLIuVcrtZ+eHyF6VhYrceHDbaU0j/1FCztY4bB864DuK18P2m26TAtlDgHRrdrsr09UcXjAgGMBf2YGAUXoOvVBvA2JmDMdExe+zdzFSaBT6rCnK5WZlzSlx0dl0+shhh84QzwRzK0OXA90zoWqRiv8icdLH2RsaJqYuyxQhkEHgp7gUeEiXpdFWzF2y2pU8cGvwfD4+WF5MBVmHz9GsImoxpw5Xh543AuVkJ3ZS3xCqQN7LlYYx9OHAyKxZDg5TH0g6s6ZAwMWvhA+VY9xPFz7qw3JMCw7mUuLB7zZV4OYSlInwla5SlJjOp16Bj+3XWt++luTGOwvhQ1J6IM24lgE4LSzwaIfJMO4PSONKRGHg+/WiFdPvv9yTVqGchGXCjKEUsW9qBixVf48PNAIyJTt/wk712Tc51T9ZMVIALQlNBrWytmmaXUdscnmZ6WN1IJqJa66m6af6obcoSuC/cnrOOZ/RJxx4L8k50yqEtEms6bhe8c3BxKfQRpQFI57P14J4FuJ4TWWEcQcOOP37gQ2rpaVZaLKkadxXo5cXcfEC/zyRkJxUpSTovoopZ2tONBmC/OVYg4iRMOc13SQSjNbinnboeisZTF1rjE9SIG/qvwCPkQBirFuINQTTKu79rYj5nvREfG3BEgpckzeq+IQOB9sIKUkdbcI6E2WSAmXTdsqvmQHUApXwUfavUquUwj5EyY5WpnrVfxxTNj8CiYzL0YGIv+7vMFb1ial4jp/l8uJr+cPPJ1VwIUlsHyDzfejK/BwMUs5tBCSZMGYJjOzcspTloL6aPijVyX2VGCRwthwzonM5mS4/2O2pOI8pEIs9hyBL0p+CVwEucNXPuNsdcqCaVT5w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

