apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgDMyaVsmqg+xD5Iv7G2wv4pOYX+fhLzDRxtDZwvKInfgK2YAuLyIDbMUKRBCMXyKCO8oxyFdV2NfGj7JDIxUtQ3wa1fwEY98gvQcTCLvKF1Fs8CrqPmIGk+ddzaQhMG2JAw21Y6PTE6YKTe8sBOO6MJaMhQhIa4v8Hbbw5wwHlxi0DTfiyT7mhu8l/+4iX2WlXZZvpDN9w0+i7Gu2uF3sD/pGqZ6bjdaqr5ZHg2iz01FOMYOjd45DrRC8rWS+gG1JSZ0GO/05XdOjGXEwF/TOy+XPppagRThSfEkaoUk7RD/20l5VDadjLV3uVE38v0lm93P0xms0X18YfbTV6Q7hUbqsjEuiGBq1QFKii5k7UKUyYADM5bh1OGQdkjKkvKGXthzEmznUjke15gVawsSseGDDC5byUtFFUgNP6joG01gpXkq60rK3VLnEtS7C7KTffFljZ1cp+qytFNL8HteBzUAk0OwS+YTI36cRU8TA8ZGrDKaiFBNpGWcmNdXtntZqlpREVN4rvOIjqK6X5y874+LWr7+2GG919aGRghVCYJTUy75ZWIwhkZar6jj0xvLqgz8oNQN730YBMmendqGyeRMGNcWDFgflw1RHv8P09d0Zv62R6tV9upziuF9sws95ObRmKTtFW6wMfCmBhW1fvc0iHKHBpsabPi1YUZoFNLktre8jD4tZvGWvLK33yVjEdhd9iq7p3qx2/7aN8jfcaQXTIne0S7SM81LhJaOOwPoQ20r6x2e4nv4Pn4YBfDR5QV2cYqLyDIFgY+NSrs9kJ24EjGrTwxksCVdfVblGmQF9soARLIFd+Tw9VdqOmqzH0mLX9dkxpTUdZMh15ZlpHt8ks6imWxEDyEcHMUHLE7Gk2oAl3nviDaxB7wOwyrZu+xG9EpH5CelEL4pgU0c1NpK/sxLMVSqmcbJcfEXBKwv9q3vpUz7jQY9ZFP+fVaQ8qtjwBM6oePsMlro0IOcft3/62tdlYSmI2at2S0/qWQ2CrTMR8Gw1Oyquk430FP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

