apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgApeRPSNPYgwpchcXX+UyI2OG140OaUkWxYnR6vgY8hla9CuN2Px7wKcUGB3qZRSVRVllvjf9v+PRRA+k/yTwRzLlB4J+Sogkb7/9f05eU/SLHiunoe9nwiHs8SKY3f/+WUXsYBzDPBzs9wAp72OCGj4NPSUzBRcOa8EPW2hInhMktoEUdz6hDcleaf691499NeURzD8ol7fMijA2UnMYkSHepxWXoBNzsnYww0s6muOMQSSUl8nW0ymYPPAeQpi9dplJpxVJVr/s+mQ9CSoIKJp20ZS9ydoGr3zBfPHwJmzi/dSyIf/PDODLFdGu5RnlLvVPYBCduExJuu0uK0sREk+ej/1WBC6LGWU/4BWwFcP1IIqSFx8V2hkct6ZfSBabYQECFbhS6lL88L+Isla2LRy7FojQa1ybHGhwbKZBLbDyOBk07IwDQqYs1R81lmyQGTT81GNmD/UU8cAZbRCDsvEA3TrVsixMw59mvpzQYu1ElWRx1Cyl7n61u+tR2uSaoXsP/qZbBiptGZE1teKDkrzKUpK6VJt86q04wg5x6xtm8/ZrA5LjMCiIOoSfaIvEQ6t0LBvGgrPxK//VA2Bo97iJrSLnBtJmFtK9p0SjScR7uT/LadddFf3OQGBhnN/Fa72xLsJkz9rIHsUddeZfDQMpsxo8sblW/3QZLeoFCDOvWocXAZ3guipv5QnrFpAaJRdGN7qXfDWoCE2hY4o5Pl+5U4/mqd94mle8dpna/1xOGeITk6QAfWqUh6LiYHpXMOC8YdsjOUJk/60ZV5373CSHSXLO7nDzAmsgssXjd1tt2ogmFUL/uJEnA+f5fRyfANqa3q+uM749W2M4Udj11by5Uz6C82oVCwr+P3wSL+jkiWKCRrxbcLzmP993TidC3XEpV1/9aRakKThxGYGDyJ2NA49W91PU7fAat6fWRON71XHoG55RMGG6JeDNfcPMUb7gOJqWNnW3HWeQQq8gY1eIPNAp4D1xyu9yO5JLnihzuAn9j0q/lugPw2wQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

