apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCnWo024yza+Fe7Ulsyzaydt+1ugZ9W76zHYA1tswmv6/JVMhKabt8JzPbqbFz3UiMPtKW75eVhBvs0PCJmURXOOpRFqJFgJhByYrA8nGYRNHH00KaZs/MeGlmSB+m1Rfv+qoEpG/8lVLKvkL8TS1sdLk9ciSrnZLwJuvS9+S/eJhzu2RalOYhz9hrQMQf0jC7WUu32XZt0pdzGhL2tT7J1hVCId7P8xa0V9wkfPL5W14rCRo2yZwOY2yOqK7q014NNV5IgOXZaY71cskhSsu6Nrtnp8r1nGkBfCGFw25pcFqCW7nqC9+gBHpmqLH56BmR+nsaXBrNqBnjsD3e/mk+HlLBpvzVtUsYlMZAX0TUHt5yeglflEXUipCK3sp1IYmHvTZDS8FXYneWeOjJWDNY1Uo/gNlHkciNvfl9ozrV1KH7D1fnTTBiRtpBzZC008uvDkJg/UONJAP/weJug+nO6/BufEOwJ4dl7ALnrpqmj+Pl65t+4GDQJKZxmEmFLL+noRdoU/PxeH3kUoDabv1h2Kt8WWGbo7x+ybunRxo72kS/nGnDUXJzfHF8C53QpZtrLHIjz3g0OtKW6NlIBb7hyxIkSteD2ysMCs8qYYCmbp+/obocDSoWaCQthpbbYMz5hpE5i/aX410F06bxrZLc8MO0vonx8hB7WlstNcr6whQtBnBf5JGbc8Ty7UNQRIeOwBJcESTDBJEW6D/wCxxwr7jJm8ViVidQs8gb2KSU+su9ifFWNQmEMkMg19Bqb9WQf7vkrAUyUGxsPwPvhbz0rUJzHupBC75DPKgXE1o3jEdD9iO6EooSJ4uPzXHbQXZ8RInXNcNeqb09E85NgwPwNaStHic/UAynrG/O3E1zTudOMAjOMyDKZLv3eCR1x6Ki9FxT6/VyVLkqOpHlGRyz0LE8l0amip3OIOEXv74H/H9sLfqSmZOlVGN3JTTEZT0cBcvlp4ME/hHrE0SeZ19z5WsjHxkifLb1C69DgvpaTn5AqbpT2PMD8QKlSlCEI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

