apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBPWgprdlRR04hudfWY6+aNmTwDNyhQQeAUpxFP8dehy1susjT5m576TaSwutB90iX39bWX7aiE2Ccp5g96TU+dfP4thTN8Yj/W/f85Qj9I0Qqx8PqGsGck0Bx8Aod5BZAYu6Cpt6oKM0C4rp5OPxLKUR2Y2t3qgSN/Q9z1zh97Y59xn6pNHT6muwNyyUCh76MI+4d1ebyuA2QO9UaAurJPFbkzAKJnR6O6Z87iMk4mWShybpS/azsmuqwQA9OzFAek/nJp8l20ZVXgzozpKrajTxN/Je+jOLrXMPnQUUEf1QvPIFSx8BY1bKOdj9VsPw/KFxFtWv8BY66Q57J6aAZudeeVIuvBJ6daFglt3I0XwrSsJrLZMxx8ZRXlbvaBmTujwc7SB0gGky0QOIcUaLazyKjpPfEigrGR69o962rZF6OHh7rAGZGuuP1n/9golvGHrIWoyKcc07bxNrNArToKl08fvhp5egM3hm7c6fiQXPYZ4dAJJ8cteLKor3wZ6WpIh4qOm3nWZj75YVfnS1Qc96al/1Vy3AepowTCZRKLvK2b/VoY2fwU/7QPDmK5DG1Zf0h2slNzPNSZjA6jzghvT88OdfGo9miAWPN25TTkeeI+6M9u+Pp0YohoTZRkLu1IbeL5Qj5k77dhk0/DZgExkZrg5fpQdl4PI8RDeM16/OZqTsYslHjLTJhxTBVopYDSnXhfPPzi5F4zCsbtXg4xmsdey//TCl+AO/MGwJ2p1aaE+U6r1VJFlWI8omfwREERckLLoUwkafDE2jQX8kvUXxgnCNqQLI3VNDgZ08eiuGNYeZoGFYeMJJ1BWF3DF3E1g72wyx/PnsJULpybdxJZaxlWoRE1n86ncyYqljzflguzQqVw2W1UQZ8QCbuAynZ7nc8mq1RBcrliaKMdDEZ9B6R+oj4tJul8BoDNhc3kwn9bpA9vaOjmmxX3EIi6WhFaUbBvv3ZETTQo2kOKkvXB78SgwQ9vs7328UgB3EF92x9D1mzE1isCdl8Pbw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

