apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
  - image: alvarocortes/acortes:1.0.0
    imagePullPolicy: Always
    name: test
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
    env:
    - name: ANNOTATIONS_PATH
      value: /etc/podinfo/annotations
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
