apiVersion: acortes.io/v1wow
kind: CompositeCluster
metadata:
  name: development
  labels:
    cluster-owner: acortesdev
spec:
  id: development
  compositionRef:
    name: cluster-civo
  parameters:
    nodeSize: small
    minNodeCount: 1
