apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.10.1"
    helm:
      parameters:
      - name: server.ingress.enabled
        value: "true"
      - name: server.ingress.hosts
        value: "{argo-workflows.172.19.0.3.nip.io}"
      - name: server.extraArgs
        value: "{--auth-mode=server}"
      - name: controller.containerRuntimeExecutor
        value: emissary
      - name: controller.workflowNamespaces
        value: "{argo}"
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ACortesDev/k8s-gitops
    targetRevision: HEAD
    path: gitops/platform/workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
