apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.10.1"
    helm:
      parameters:
      - name: server.ingress.enabled
        value: "true"
      - name: server.ingress.hosts
        value: "{argo-workflows.172.19.0.3.nip.io}"
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
