apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vela-core
    repoURL: https://charts.kubevela.net/core
    targetRevision: "1.2.2"
  destination:
    namespace: vela-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: continuous-delivery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ACortesDev/k8s-gitops
    targetRevision: HEAD
    path: gitops/platform/continuous-delivery
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true

---

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kubevela-applications
  namespace: vela-system
spec:
  components:
    - name: applications
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/ACortesDev/k8s-gitops
        git:
          branch: main
          provider: GitHub
        path: ./gitops/applications
