apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBt/U2PrHgiHzP4V+pzfwGtA+epX8XWwk4lkswFEZDi27SPWyvu9UBtpOsnl5TqIKjsZ0uQ6zSpfEF/16eZ6chsfauzJoVQ/Kxht0RI9pTKEGsLbtvl6VW+h+5varKxF0sLjAu/h78FgGj07NbJq7y9tWDQZb4dnVkM3sGUqdjsXyBuI0UAcuEL3qsLYbo8rGEK7SiKXRg6KewHNSWklWgW/ewjkBRnzcAmmFEZuGlPdW10Lgb6N1qW3gxjnXzJZjC+mHmjJh7TfDvjUTCjYmbHBy5fpYqxMak1uZbZNJ5D82Qmthm31xo0X0YSZK69FT4XupgNSvkR94GOWb1j1ZQfDCSfCDsBRAn83E2xsqMUqk6GZMxScUHdQTGM+bdfgaRl0bMtlQwQd+6Fpn/YKoccmjULxl/WzlLNWtE6p8lR9gPpvNmdkJfw3NaKYIZXDUtjIni8NwlC/J6+dKpDm5c57Apd7qgBm/ype61Fn3rN3VWyonlNqeWXTU41N7VXqm1hyz7iyIc+9iKr6SzBq/8vDDFNlByBenkIcRUvhdUZEeRAdJuYVoNK2nvNmfihJLn2iRFJ46IA94Mzrqni0eUDx+rX1UsBJTkXnOmzKnsMKKXP2v4UqABbsqLvOdtRwuEesjn5x7XaAmIEDS3L3wjW6l71dw8xfkPznXhIqgLdhvuVzwR3jocddEG/mkD1z8YqDe/uaEt0qLy1yrJ4oBZERzCY4uXnnmAxf+KSoBtVQ/pAj3hVlMR8xTzlSDqqFKCoYjHm0BgNbXzqdF7WU58yi6DEIQN2izlN1//XBl/WecvjyhBWVnCj8HGeS9EfSsd722VWwx+goiLvqEYQsppELV1fbEqtDUg9ksMjwpqhd7RaOHb5MypXDiN8dfdBlF3cxMBmv6goShr6TW6w5zgSz7PcM5orLDyKrmN0p5TKbwk2xn3vdxWP4ggVXFXL/6tsstF7m6mNiAqMNpoOmT5W3ifQlMVnJGxrpkIgIRj3FvWCUf10SaSZB+zUSg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

