apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBIcZ0sKNuxdTZG+pGKMP1JJok8mNT4pa7uv6ZMMGuQnNhpxPBYRH5ZteVFHXVArCC8NniPVMexTudUumqxc2uwLZQkZPZiLE1jc20jBXb/gXrtQSCrds9Ti0a4w9dqGsA4rMVvP109Cpjq1VgxRL/KKDfAJrwry1YSeF39Dn5fQM0IsN1mzTuokdXspRpy9kwyvuCjJUDOX6nJOoTXsnnSFc9rVFNLjlhOBSfFyldu1scvtw93D/gxEriLhQKy4NZCl+5kMAz8sFZyXhIgTZctTYaVO43hoQQLy0GadilEjfbhropdmYhvLrhS5p8eeSWJPmdJVGcyrRDrEBCQx/vKNkD9AGplxRRvfwOslA/VSShQr9LqqnGMlrT+FhAyVDIiSWWs0vVE4brj8nT1weyGFglykbRMiWXkHJkCIDWbSqPeqt851oFHMyPRGLjaAWG4oBrHj1dUGC57QAU4eHcrgv5OJ4ZnXdWfMz3+qgwubGZvWnBGg3PTWLaDig5C9P0pj63KFdC8mOigqSWF9VopV6Rb6k7HSmprUrkDhylyekovxN6VhzYWKInGbH5fEoSX7xSjUvo2XbsLfdqU0JCM35yiwJLo9yjAkyyMoO/z3LBoso3itI0qdczNVMgrVUxoLAKuW/45DBThyGvE3emCj8zANXdzirZ4/AIwGdz3y5GYJQPvr3xvBSeYemAN283nP6Kh4b6L8CY8DQnGi8YPmnNyvVUxI7gSoM4quX4vtSOqkTtF09viiMSdtmUeF/Nnnc1ZH7xoTFftiMZIPdjSiAy3EawEsWxzeB2kehO+Rn121TB+TUGr/fz0k811bn/Q8tK3aFUCFVaTJWIkF9j4/vDczkK/r0Yj+eg7FHQHNJEK8HmCK1qq2pEsSPBqR+zHDbz80a3XfU4V66U3sI8/m5DcOSbhrqYr0f7qS+H8cyazlxjg5D1E52XCy8uyoZ+rqAqdl/ZWhFNgtxHeVMAQp7j5pt2VolW5lE8oaEw2aEkZUwQwX/knDoM1Fg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

