apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-provider-secret
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCIGCqkhWg/+a67VOF1EM8xt17G6gLOoXnBbn4sZnczpp4rvRncOBdIiqfTpJiH4Aedvi+CIpjQW+stxOXiqDvPYu0KnByaoYr9auMs2J0tkFaPeOfCPEkiPs1e8eXnCZkrNuKZbNeNF4CZ5xpIEvnudUA8kfn5j8pcB4kQgSMizQZsLl+cBcNHI2QThy7Dj3vgcJQgHhXxJel5gHSoQu/UIaJXCAAW6iHX8hEF+ka0lLytKmn2Wo7CHJ8Jo6C84WJWd69MeZPJ5pfpXaPgwpZA92AJPuFtS6r8Dw7hD1C+Dqa+r5JwKc+KpRPy/622Qst/8ks1k3+AdIG938veSpy0phPGB+Cq1RnokD2+Nony1lPouxJr4Zf1kexWLevi9cQtoJ3Z26zXAFByDiuV23hZiz0n9F+rAp67ZR9ODvOaVFxgtbkxy1SLAiqh5FWg+XhbUZnanQsfkI10L10RGvPVmOuF6oeooikQIWvCaZezdHjOc5OOtqGWziIdbmxjPCiESnaCDMlSkYtd8gmy4gfAU7qdqhS6IwLO/lgABm9A3ZYZJc05zf3Kp0F8HmzMUBSUuvtNuAJMSGrn6O+z8SuOT80pI9dMj4onLWafLSKzhilPeLSWlEUYI4OF02s7T3spvzoJogVD5jXoSSV3WG9iapDPIVXphzmNS6b21wQs7GsqDDp5uNHod6PlokE3exHOTJohHqJdZkgTXeqWpXdIA/jqFynXhsW+l46L1KApJYkmxs5bT6Zjy8vz7vryLU03yg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-provider-secret
      namespace: crossplane-system
    type: Opaque


---

apiVersion: civo.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: civo-config
  namespace: crossplane-system
spec:
  region: lon1
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: civo-provider-secret
      key: credentials

