apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-provider-secret
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBp2tnfGfrrMSe50O96T3KXiPzY5+gAwoT3JsFZ/mPhW63ZfJyKTnD8H+p58vCpR/1ZU4Rp57acJIhCXBKwF5pJFia1R55RKNEe3/siqaq73mV/h6J286Gjtbng+d1UDbJY+PUPET3GNEc8bcval5WCgHlehMAVNzFqXNK8FReT9zRfHWNLN+d7QuVDLkpelhmoN77tTqsYT7il93LNFFl01kDeLl3AnViz/lAX76smxy6t2RhZ6ociv1mfpJZqro2tKaWC7GjYWRMZ0XTBGZNP2Fw8k3i7R5WnSUPc62JaZaj9DJ41yDFDXJ+hDLa6IfHS9QDm/+bzODVL4PetBjsQfocxZAIL5wkF5tJJQOV9i3hyXpLpa/fRmperSHML5Zsxlea87lttmdmYvRe7gnOz/70qW+hTm5OMHUInQ7Vs2LzTNmNXOCGSX0ng7xIM3hATpgtJI7lofcdwTii+gTtxI2ePA9WYwzBnBy0vBLZhsKAaWmoNonR7bf9qitY+oxgfkr9VtKPnnqcViAu5esizcO7Ry+5S6q8Qqh1OxNoz8P45Z2aU042pJU/8KjX6BBlx/TkYZJZMlskxlB2dytd0/s3PxLG+ba5VdgNgqfbgkQAsdfkpEyFX7nO/RPnJycC/CKMlUGbKOdYx+AzISh1SgQv7gc39CKlYAKl2LtqIJ83Wh6eAW5UB00CISuWbQP02U3ZjfyUSOdPumi7d46M4B2hlTYgK5IwuJ7BO6M0DxnDwFB7i6zemTRYWko0G6Aqd4A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-provider-secret
      namespace: crossplane-system
    type: Opaque

