apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-provider-secret
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBPmPBbCVlv/18bWG2yB9GccpuHgHg1VgO6LaApFTIwVZhJxyJtjXA6M/lhWx7qk6uDoe/oD06JzGEJq4WmX9DeiwzWEkhIooFyc7vw7HBukuskCgSG9tfSxLKNA0VFtDYVfvo3kyMrPBCsvfHPI+xKMvVFCrA3l5dDi9XCHXMVqlWPJuyJF5gUa0H2Qnurk2u24Dp8XNf34UG1bqzft4hshIPvJGp+vCfUYK9vhI+jD3UL3HxFhiwWgDnPg2A1DDcEpl8tG6kRpCqMClbI/RL/UnntCWlPzVVpAUQouj6WEjN+0Y9hxWEiyRm8sxybjOA+rnubd9orNvmmc9TPNHX2/x6OB4lk1sMsF3/wHt/xfZq7/nv0+7Vyw46vJn8/Yq/cOLtc1KX3wizrXpiVMwspZzuYNfiQkdQInhetpN8HFK+bv+DDuqIeq5gGQDRBAT68X5LmM6kCLByEy2PWm6Xl8hl26WltC+eRUrqKJZFUknFctLTi/OEmew2seGLgfEiT+cHbUhKAwiHdZriM+4T3NEjAJINNQN8slXm6sy8S6y14CkgN4dG7yR59yNsGLZv1KBWyeXIJCeAvh417Quj4Js6WYSip1BFbQ56YdFWR1zZgOAISHqKX0nAbBfPsQwx+LEqINccplaMUl5SWzXJCygYkG/3oOiYoBpmvC0pkoQuGZdGdTwXtKpuCVyptNlqk6YslYQkwCRjdfyg1B5Wx2g+JW+924J5tQBHGTaYKRPX9Af5ASi/IW+xHeJtssPKaUw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-provider-secret
      namespace: crossplane-system
    type: Opaque


---

apiVersion: civo.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: civo-config
  namespace: crossplane-system
spec:
  region: lon1
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: civo-provider-secret
      key: credentials

