apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-provider-secret
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBciZxzAyCU4hekOt51PVvvZyBLrXzhVIZIH+KdptxCo4JLIUN/MlAricpqUx+cTERYNeNcglFYgR9J5mmX/W+n+DXKwymp2G1VI/V6srST0Uc8LH2qOUjLkO6fZqn3/HjfFSQEGQzoF/ZbwlLouYdRga7qlhPSkEu7KzNiP5nKpPlDsXxyhVbrtyVuIHLMRpZvnPnni0RldJpJdj09deqPJL8FnjSk4eNi3mYCDl+TQyI7khiZzduhylFz1sNR1AstglS7E0A1mYA50pkdZ3RLGGsiMIq8S9g3NDJMOddfX87m5UvBXQwc7ZlyOChgbqa0y0fxU+w9llc6iCmuvkvFLiabsR6LYC5oNk5UtUS0ZzADWzzaCZ0nIGi9U3e4gRsSfGkhN+WfIKfz9vVIt6/vLK3xw74NRAvJDDKImNF3Ur8eWGNHHa6BzEknLzZoSwJtmBlDq532HpSCWUOoZ6PyRShA7KHRuYbF0ywc1SvUuywWKMMvxRG5V69vtQ8T2QkCTM2Bqg11DpURQGBgIwO+K/pmyq31saUl257LAwrQatgZpPNM6w33l2g+arTJkPuSxr0EFdUrzqVbnHEEFB2i89WFnVxAZq1o/bRQUD/gYBq/VrMnBCG9xdhrsteEH5bRYerghCKS3/A0v8+iNyKtONCieuLXaj6GBq4rbiVgPQ0uShvkDy4QsGrWFKw1/VJKOwTQexCVkGXUg+7azxG/EyHBsdVGF5Froq5FG91OWBxRVmRrhhXhInr6Hf6o9CawuQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-provider-secret
      namespace: crossplane-system
    type: Opaque

