apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-provider-secret
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBYGyPGt2rSHv1erurYfwfUSp8QKQubnAlb2kGmlmlEL6uO2Wqnz05UE0UyRg5glyeo3Gr57EUaCU1JDyu0sXuDcnm+sy910tx8/cegjENiHG3OLV7FxfdekxHADMyp7VXRUZiwq57pfv7q1BvQCMoLBgWINPC43wmAqV6yrb7RtNfWKUUHd/UjuH/wPK1RB2dlbocBxQEDlUFkkTrZxlLriapx867dlYEP6haLNrWSr8Kr+ftwdDeVeoVsOwgm3RYNJcy7v/gLolpIXJinfYeBAZpx6dizll8q9thXBjANn7xxz9IeOvNNzNVCrqzd3MxpWd8O3GW+yI+4PqsyOSvWMZffuOwA/NUBeyGGTFEiqXV9+PHj61h83cG8akpN2+eVnlEClnAm95XGTlxrTdjnkLb9xCpEy+9rCwm1MuE+O7fmUQ1qOAdCWV1J5wMa6CKyJs4N5CoOBLNmE9nyRufayMWjfTSZomQOeKebmoT9dsKuprB99RJ9WFWZPIhHtOGxdpn5L8QeWRRGxnx1uspBzDOr10z9uvS4vC3Z1clKUslSguIjj1s16v0OLDiWo+PSEgt3sVLatUNwUh5f3TuujjtSefz/pghvELXCZk6yj8JPzRKjHLcDX40bLCPjvmSPxVyZYKCmay+mq1AhGUvBZSLatrmcBekdQASZaPgOYCIDoSh5aah6rCjFNsvYfhRbprA0hK//IQC181QT1040BrgCR5eWYsvtoy0FAZMdUyICFCCk/R1lKv584I6lPTkDoQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-provider-secret
      namespace: crossplane-system
    type: Opaque

