apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBDcR3pg6HZKTgVfF8eApUZMf7v4CkZaqJTB/hH0EC4Gjs1bxQM2kHzgbkaZlm6lQw7Q6MGQi4I+g9lIZbn6amFEIfJ05leqqCTjHYV44bCoq0vKqCjFsDWxCgyvvkIvNJiykQ6KpQEGjqBdBzwy1tfZk41KOhxcptt5dmMbeTswVXgA2ZXophNkIn7zjm17qF8H6pxjGEWYlLtTKbX2TCwfxNmCDpZaJl5vMK5sd0Q0ncJM2a2pC0VFswMSURKkRTxriQUpZTWXtNkcnAOrh3z/2DW0pU6+Il31KVcjOoaZgz+fjsHSdYPV4mGhSOHaooeV0HsKp145HZ9Lf6c+CC37+85qc/aJSbrjlkU/KWs43eoO+Am27yT2atrKQL7ix82U4YnIh/1QO39ULcf1+Fdj72jGpGiOTbeDHfu3N8xYfqJz48UWAD65/Sbrl9ayc3VZIJzNVvu0aaS0lOc3AgjSwpqqtol1syiRA2fNWMrMBpFJfThA9gdh4/lEUNekBxPekf7w0aHmB7OvawfLmXDDaI/QcFaqwZlu1pMkzuJoqQqNvYJhrIzxS0FnZa3EIXl5BsGYDq+DlqlL+0ASkChHgoYTz4mkVQPyaTpn4PF651qO/R0Ptdw5RTSfqpeObRhv9kShyUQYL28jPgFNss9R/1YClLxXHNTrJflGfxrWfxCRtimHPWus8Z753tsp9lQbfSYZkRPojqNLprYNq5+V+UwDGqPFwGL/D7pchWIf5cyrf1btMcH23h/qtKxg/Gh+Y+KO7Yd9PLyKOHPlJYXh+MUkTfs9vpvlsVa6z6K93idmxFToQB7v3JtrsgoyQ0mx9wK7M6po9oDNjHEgEwkBVL2Ery/R2dedg8y/u2WrafbancSa3a6KX7kTQ1YLSI836L24Pvnb5fmFUAMG3EvK0SioFIf0ozTShmXXmeeGoGhUGmO9Ev8iPa5SsycTmqQfQaSAb8Bq+Zxz3WeIJCuO6922ty4CP4+iv+0kX/Bl8MzA6uUupebIyrWXw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

