apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgB0soJNMGL9Cokk4JY7ebGfGp9vZf26RK5NoxxjF1UccnjWMHrckqIa5LboQCGoRBhY/0L8xa/XChzMTaybtVTx9AfopvpjfN51pGjUaLZBglPRDJ+83Bvk4DXCaUbzH2L2MAtoF+XkM+zzxcRzwei20a4Kr2gfMhYaWnI1PiKbLaOuMefTNTtjNfpwnk+a6Tdd4lVULL6ytVDlzqIAltLbr1kgAVhYC/ZjVzIKjQ+YrDxRfByIkFMabozXcSPixa7azKe3AzXlwHuDqkfFYNk5wxiQTuBwPjVjYKs3ZIIpBPd5syUokYIHnO7cGI1OEHwNndU9b5vIOh6z6Dt9/UFLdTZKfEg4LSONJTVJ7HfmqAJ1ocuFqctGZehN66efhgxLvT+0A+169fb0CgAXCkLSZj31P/QBgMlTH1Dnm5JKn7UQAF/erTsJ35CY0E/MaBN/gwXjJcRrGnxawpzOlP1XlA61ecO/i5PEyFk1ZpBpA/qnAVk4IojsydglppY58kLxIhGuacEO8U7iaV4wEuphrnuwPSi0Rl295ecgoa9UyjORX29bk3ikumcSq9BACQtaWA7333dz8TTeBpHZxTDYTLJ5JpqBGsiATuGA00j0nA6LgyuyShtALz1jkwUuubE2609/G6JfKj1cCxenSuO2ajfVzxkHbVz5K7dxmafc4yYCT4DoaquMZuLpftF5drMCGNYzzXeSdaH/61w927SRPBr4OSCNTtT8FZyN1l/TnGL189NsMet4QSghsX6BCyg1qiWfjaOU0eQbr6zlA3ColQqlNkS9bEn1sGay3+V7BAFgENGrGHHRj/tdAvAUD3Oqq9Qj6juTaR+EizJgKFz5JE7fs5B7wXr6zo3bRk7fWtESCnX4fpezsNa5TuXNpceOdjRpfifjJuNtEpgmEsbhwbvO7d7ZweY98f5s/mw5fJm8bDNk353GS79XJKSNuTI48gAoRuaEHWXOwP9gJAlQdWZUTU04Z4H7Xpk2BJS8bbdqA4jB4J/8HvkYvA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

