apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBMWW+3yShcy+EOac0XccFE2KeGJ+mobEcyhdsjdnhL3m36sp9+P91KQycyJS7mpmCC5pLqmwdnCjQXcqIqmuiWNdxaSFSsULP7ZokqwFPiM0Qa3qixv+dVKdRg3wqYO+IN6I0T28Eoevk1mX21s5K260d0l93Sd4R2gp6YHbE2dffGyMZobtEL15YfsG6H37RCU0/rlkZdDQ2FthxJTr3WZc5DFpu62lo/343P5R+VKVWPejAoU+k8vcjaiy4L/+BShkw6OvjUnOz7vHkRC4BtaiFmwQ9F810H9dLL+lsz6vRkYJF3D3SrwGpcpj0xHuLsr7pNXD9sHx793qwaICpdJfsJ3N/wIarUFsnxndw4yqkzpMzuiPmyBjkn4ansWWDDo9uBkf2r56dF8zN8p4YfLkuKJYkf3WaOAj63fgbstU+a+pS2p2DqxzMFwzRmkfV9/Z9SgqLiTWqpSWjLpo+oMvuj33eGnO+T5U38e5DOpR0C0G7r0QYsvZh35l7wkpAdo+Y2z6My56oB5W0yw5rINjVJoYsvIg7d+2LI7JvuJWBftP6/PIJqu8sJmw0hLnNAXBGYSPBHOZ6YPPtYJDZAulO5Ds7gRheyrSX+r+QkRFr6s3LFixOTfTg2ZxTHDDjqRdPXmIFBU31KAJOcAY3xzGV5tJ5ZUB/pAKykxDNID8sEc8B726HZMTq3ggyWMS3cw2eaQgMMHZXP957fy1BkAydaQbMemZ3k17PHfboyR036m7NTk7oJfiGmbW8HtdTjEpY7wVzpIWJuu+2nmhz5glHQh4BOwHgSxqjOs3DqSRxHl6hQPMQt64Y6HT93z6braPQ20xPc0+BrIYzOi/HbYPtVgYE0dL79GNyfPYEywT3Lbv0h8Jx6ApdXKmNPEq4+IY/P7P0Qk3mojCdQsDvt7XmL4/I6PQzBOEncZYyNygVmxqAb12Ehx/FRFh0vnzkaM8EMiTuy9HRBvoOv372xx8qDR04jDwCdJdr57sPeZNYRB4LaydJJQEh8yg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

