apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCEGGpEDzaMRDEregh+9MkcR6sk/5DXiVHA3W4DLe9OM+1n3ZG6fQjnTw0+M4+E6Nu6Zokn5LBS0hddxoXCUxgRccqhjls6hCg+bW4BJp1/ksUQJlqtHhML79u7lf4tectJYUoMUq1vpSIvbBIDNwb52J8RqmuVBDyXTqDGz4aIHWteH+wgzWu59Uj6gju47V6cVwmjENgMcPjnXt981SybWRhwnpUGlBRKvLvx+8tT7mJWyMrPU6S5FXmIqXG+tiHj/I1MI2FpkvzYn0KYDuH9wgCmikAnPmj0JGVS5XqP89VKiYmWY8uZ6jaQwqCg2AQea+2DG86AYwn18pps+i0pIFZNumG82TPtCCvwCdc2rzEz/Jfs0eDLmghr7lT8TTLh8ywiRY1R2in7WAJk7aacqqkXk7QWf3P0GuR1zfEeunxOEG2GUl7doQHmDGyQyN+URwiNMktOXBrLIVJAZhDW+I5XEAL50MlhbT6lh5bpgIRTq2whfemi/1AWpX866DKOdszhZvhTgi1MIugBr1SPBIXJX1GXu5Fqd5ESq3ipU1Y0VXz2akQTBtG/Pt1zi0Y7K3ff3YQ8aUjDUqQf5cNAlwkSNucbm+xbzXsH3Z9jswEVDl8rsXXMnt2hW4d/8J97dZPG20ZD98ua1yox2hRMmj9ECuYkSaH861hRa76sZpUX6FRLRZf360F/SWJ4MSxBd5u11KgJ3Xr8axYvvN8Uc1Y/eFICOPUV3T7vbDDRcrjGVLpkZ6Ttth6T9Q9NczD33Pd+FlaMna37mseFYoCLkK+GrQjyjvAIed5kR065IoF4txQ9HODBKyFHfdp2XFUE0RnyuRiCOgb28T0RkQGzdrzl/HQjMLDK0KLy8XA22zULabG9Uo8j1lgclssPSsNUgS3xHdhA344fBxEMchf1QPnXoBqbH9mZ5/1zZ/ybHunYPCtFNnEA0HBYtWZCnPeK5tLbrS2kbiz10z/OJd6fis8eAs72ubNV0rxF+27IlxrAxC6Wn7xruoh9PA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

