apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgAmHkkg5cDue5NdtwVAJkPhLszn19uE68QX4qPAChSu56dEVORAs05JewjlckSk/nvIA/i9PE9Y4f3az2BkdYuqZjptx4HEzub61BpfCL2PRnhUNvx7LqDWPzRo9rytdukJUFAKy3tzQHMnZlRSLtza02bv5oGjkzicelLDnOfRpD/D+OxQUaT3bjO5x+xF+HF8DSF4iFqrssUlrHPdu5Msu7bVTNsUAWBE0KryHgVsSe6e8l3/BxK5PJHH5phpRMndzJ6yF3eDCbzl4Hgjg12pEfE44A01QDRNa4QHLOE53GjRCueowwXsR3q9P3gFsoyMIt5/oUQYwumx24ICbMby7Mb8f7JPxbriLDYuQMinq/HYn+CwTgF/y0bW3qNtzVHWxXgS4bFfNuNvHNQzxG/0o/v5332o66/hxdFgkLiU8IDZ+NtdRnpR+ymmpKE3eiCNy4PvP3EAF/mUboveest1Apre2QPVsOeHs4LRubegw+7S3yFOsrDiZUu6qwtpMoJfNuVONmZpsnxnHKHp/XH45ZMbgovbqFGKRcb4nrltJrqKJf6FSVcfWTPbZ1MPx0UFKnSbcGhxKdmdATprk4ftklcfOj96wZsAnmR1/ZAphLcOE27n23xeuAEZBetqKkuMfHg03BW9uoPT0sSqFxkfoygx83Fq3+YsQH9aooPJomtbRAe/egULGMRa5qdY5Q0lBTuT3s3+0BNMjyJ+Ld5Ok4twgWVkQSjhYH2Co5O/b7sDV6Jd9AjWecD5DuAiFauPotrbc7AXq8VMKmlhj4jPQh0PG8qQTVeyxV/uNmnX+KlDs9/lgeL2oi41l1W+B9hiiApjX9f0C3a3beUdjZJvk76YCUvhzL7lzmzxVvYbcR7/veGgEihr1HtBb/Gs227qKVBI2Y2Sef22f70svtgIVcd9hRZ4X43oMHZfB2+DvV36GMP46lKESKi9vMGQJQyymhWBn4HIoNgfFI6UK5V3dAqksDTLnjGts1rjMteZI18zPuXH+co/FVNhJQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

