apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgDXIDlCWtIwoymJI7TgVkm6S0Sa5OTxtMlqVsDHr/pLGhZHY5eTH9GjI4QT2HzjlCaccr5wRKo4jXRLN7zkEA0ekQF+RetlkieumDo8NabgHsdetLS/F9XHRbUrM7i5yBnb5fqRjLWzjAdv7crdaEDXCdRvQv7GF8juK/frACCojCMqWRPt7GsTM/ZqijqfnykuRtwxFCla8if8bwgzDIbPdF+DBw0W4xPIZj09ZXTWGCuA5HUVKBM+Zzt2VoSkLXcucT27MH6dwdk0852N6oGsjfkm7Qd77NB2JGiy4uSqRGoWHhQrLIP9fFim8Xq7L5wzu9qwGYLJI9TW114Vvj4K/Exmp72OZM+u5dXLbXscB33q3bMXOGj2nEERcCJOAE+3/TxRkmxJt6NU35ZoiB8B+9A6uypR7NifVWKlC1nkI8jsRNeYc2n2CFSVccvAO4cphVSJRy5C34Rx0NclIuRNXpU0hug0n/MXg/8M7NBEU4sXMtvglIGomihjvqpAsKSr0TAot52kKe9DvsYKkSAAAaBG9QhLL9q7KuAhwDT8oyqfDV2TLcseF67LJlhA0TJKBlPcT8Yjn//Iu3nBD6l8aoCw2CPy3D2WtgnbqSpf8qP6odbaPBGvK6QEhnwGBobp3yb8cmh3F7of+l+YByCTMo+nIHyrN62awC836o2yBalqOl4HgX/9hFnBIvXy4j5ssF2xt6o7xsnb69Ti6bCf1uEbND8wrk0L2PppKOO+7cufgJ0/WysQ5OfU6dnDHvUm4u/4+myVSMls4qoyq4fobgew8Jr3TEtfBauk1ApFPT/Hh4whFMPsrjcdvDLzidpesOOPWdyQzfhOUx86wbOCxcXH9aVxznYCtSDsZB10FlHbJQQcHsFqFLdl8EkBEywNodxaGskVwq9ua4sbh6bpEqpOJYbCR8g2Ub6wdU9hKOkuJrGda/odrlr/twHMk0JRiBCFPtww1ZiqgT4fjdVK9Qy6IZl16mzynhkbKkcd9bD/OMC/KZNEWY5NMQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

