apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCL2FHGG/cwhyHacT3QfLDs7FNOp5nQF7AoaX2RMF1LIlB7Vj/ZNHttP8ePH2v0DGc+hLUN9g13a1c1kYplNQb0PN0/cOws+24+n/ZUO/2JYh6uu5k1zH5GVt6UN5XUmoP5wyHMmSh6VQA7/5rbiGDF2E5oMtDvWQDfGMCZ78GTdrUvrPJeahNyy1rkcmm95L4v8KWSBg1+DTKCp5tFbSvqGLhKHYPEOw5CezDUmpVkku+EFa1sDKCviIEEDWx7hgo2fQtILooUkwI9iWFrCun5hGAuNfJYxy7Vfyb2tvegDcH3hyUZ+h283/2M5CEPln2Lo7EM3bAvC9BE9nBCj0RWuLC+MGFW9cmS6cXTjIHh5GNBIWizzkeijSZOWJ08KpwbLD6YRl5LgNyUH0evqp3J4+6fXO8LDWpLcMhoL8iY/y/G/UM4YqqWP1l+mv8NeclsNly1VCZvVgA6qaXEtASA5Cd2GI5KPHsjFCT7jOaRPdFa1diCCOxyGWz5CQpOAjy6u4287uWH8lblQzm8XoSPhvtn7yf+4Bo3DNDHbvgDcQBowdPGbrHdRRlFPc83BnxbCRnRQ7cdgXYErJxHji08fiC54DfGNPx7ZCm8fO3HZ4C8UvitCia+xInP6otOjikXAJ8u3I4UbRqBJdITKdXr8u2EAOHO+80zwvMk23kG1WcF839O7xDxVccuX0G5EkIQInY/UhAsztlbCrW1sNbwEayQSWvGogNIjQlfBlASMbUC/299UV1rdsv699KlEjS4qEQ93SXPcPsGE56uwl7EHnZhDstIJGXKPuvWGeGyHoRP5Cc+ExwL1YmAVUE7u18yjfmziAgapt74whcEcQffvwzWauVIINXWoDPILhFxkNkIZ6vlrCbvsqkcoOShAfwbithYbNLtOVDz7bYE0WaUNYFbzzAH3GpwmgfqcGl9sp4wk18IOFiTsPq+r9wMr8rWjUT6zFQTiUMJrzu/M+N85/g+u/ofLrdGygR7ahHr7HgF9wLfsY78Ivlzmw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

