apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCSxKGUaBUXdLjWaWS5NUBHxfuBw/J0b9PTf6h6eB4jCbOQCmCWMGY7dKFa0rD+eBhVwJtZ8HGhp0gPCSaNDFgrFjUeovmPk6sHDhujEhZNmVqpNd4K5HG05vfZlOtnlMRSLMDwnPQOz0XuiXiihu9D1itTc5WT81G28i9TjQeOwSVXdQMHiJy9ZArd1xl4pyDjx8WxkT8sxVWcRRIF3dJX2lbXHxV7kezurxmmmdkxWNUuscLIEbqpqOXJuM7nais6JonGFrA/vGaCErrJq8U6qrf1/V6enzgZsqQakPytR8Uraea7nJmaVGi2Y3tHMmDB798OzFNh+jKT+FGeu3kljhJEx6gM2IZA/XzMDFvrMJ7ZffLynfHXEKFqeUL21SnXx6MCkDPGXZ9wLbIZkvSYvHk3BT0H7SeafKfJ22Iq9ZQ/RIEp9fHJSRGlcZ2qVT9X/kkxSMCXxw//wcgyiYZvlLvBDfKw3ospp5wBmDM9f07pXZ5nlqFhZYAGnqOKnmsgLlnuXu+XBnTEyVYNvH3z1EZ2AZd0LFt03FahPENLyL0UDfug3ZSPTzhULEgWtc5wVTD80CK7Wt3q+bJuprNfvrzCCCSoHOiQ867WVqrf3YET1fbYPE5WBqrjs1+JsqdiMLhGALXIln0DAFExGvjiYIGertDM59gA2yaUAWhjuwVhEWL+FQFSfCEQOTNYnBltQ1SWSv26OYKVgekVz7BXdi/5h68Rm8xNamPiR5b414rJo3w18n/5e8zZdT7E1XZsBZaPgFaHGKEXYAXrDz7ERL3acdrN92gAfdFJ7pHVub+EPsBpQ5FLse65J4Q4X0QHjixDma4uikvxOk3HAL2856o9UQqIJaod2gn/fz9IYy5WZQruvvYbgNFtL7RysKtTU4ExILC3gEchemiUfIEkDS6fxiOaEMY8t8i8k5AjgtHK62qNHbzDx5k6f0OueGjUJ23HRU/Ev6L4tZjb1+aQvmbbLcjiaQGTtEKp8bvN1fMjHPyQgJw6lLrcvg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

