apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgA+mk0Cl6XJ9wCbr8FUSiuLLOJFQ+lvDY1Dv5GMjXyMieuihdHiU6d+V1K07fZTlD9B6L5l2w6oIe77T/w95nErCnOSXKm9C6t2lTS4hqlNEnq0iXqj19GZe4sHyp+E3VJUZzCJ1aHOJ4PS9e9f6IvnMZnK6wxu9ZzfV19tnE7vqnjFZBcdW+xDNxp+2AJlGLrBycUjib2Npcgv8Ih3XUEdjZ2nXC+T6qxxYLi0V1oODEQ2X1VXf8TyWyhhd2+sIT2MT6KyworML2HUK6eFQaMxz70B2AfNnQ9qjSvR4Rf7Ph2BxrY1HxvT7X3xIEoD/loxNsdaC7cnq6z1srCn1B3YZATZxMBFXO032jwySSz16OyQjgdOX+/Gzb0j4duFllWC5HHvu+CSdnzSy92m+KeaX3ERScTLVu5GqZOA5L63t9BRMnvYTP9NCKPRxPQmBqQilVGSm8nLry5byKIlWzXvoG1yzCeBCRNyKpYriJ5vyvEgtlnQIRFo4KyZui77yTU4PKlft2JEub1kBUonBYBJIC+Dg6+EQOupwEZ3AUwB6QHD35S4w7tPtAI0C9mbToE7+Pr8nNVqRl24PNBOMORrYiM3WF9GETnKxc4EqQjmf2XDM3el2o8sOa20bfyilqcbScNsXcRuma1lqah6Ix4wEEvb9lADQjrg5ozn4z5eSB8kwqIqcQ/giafpeDLhQJrgndFYwzph1dxM/fNBKHIuLT66gWWzMMMozQg95l3EivsaQg4Hnlb7RLHxh9VWD4VnEirlyw3fXlKHeAFqF4oA+s8fB33vq9mP+qRXWFEAbfkpgSGaQd8ql+FAGlHMV7VkiPQM6RVdzWiWTR/K8Br7gsO3m9XPPrptBzYH5Q4s21VZ2femjOdvXeciFur8ZkB3zmS6K0AMb72P9P5anBm+VS0wHCdJvLqEFkZ4qFkVQwaT6hY5Rgmhw7YdHeI5Aw6xJT1doSdLtStlPmjKYoRQBAImIwRmdrHz8JZHqCAs8W69ZvAguuKArEs23w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

