apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCmBkwfhMILGdB46/dLSlnW6s34Snv5cvZqIZHNbmDqoWquK2URJbYBPvoaUL/FcQi5ER14+e8BL6CkSmfNVM6GcheFpPudIsHUwWdpIMM5adknpE6sA1WOZUqJ/GIaS3V9Ouiv89cNCmbN4R5gJrUNQvqUJfcLfIRZufYqptaR0HYTIDtEcq/aXV57H/33a9P/TNGnZv/XLy4THFdw5kq0MuVNQDyJN719NcxD9zkOqzLeJwDlo2J3lahiI0DOaTg44Qzhxb80f4zD1s50ku6P//9osDkHLBdn4E6Cw01svj+zwpd+QRl92lfJJmVm816dZeizR5E7aCSwHqFfslziD0ca3QSP7qvPJztfWVPBbUmK15Q2CdCGdP+mvYJBZXI40J+ZO5PWbOQT1y9fHEixJmAIWzrnmKXvVuhZdirx35eaYc3J+lKsRX0EjwYC5OiTQGWZ+PhcD0FE+g6eoN44oLvoroMkBAKVgL+640LIh6JR1wrj5pz55n3El2uylUESaEHBGAk/nRSKnIlekpYZr6yBxjbdallTmtqMcDgIyCPVj+8xySf9v29O73S9nwp3p7W0wLHZpVyk3HyUP07XqCmbaM04eB9j7i+sT4zibeVykDI5kr0ElCBP+ZZIH2Khp7x2QepScMnhRxuSxOE9l1SxXOczjzaJpxr2j2MPlhL3zhBRsxgDw4G4aTpHaA15O4l6vU+1+DJNigXzlE7B0gMG6IXUM3960ysilNGElzTEwUY1RN7YQOhMcMxFgs2Ceg90Mv1THN+CKHtA5/8l4mcdM3/hO5bw2rblMb8FWA8N+FS68JAFgwwXf0yr0YYqub7y0C3OTGoHPQQIFSnlLyC952IBbTQ9tSpjW3PzTRzwivlNdByyhuDuwZt7xTiym6QgVSOp7LKeXCWKKbFlKBa3BQajd/9/ACMV/WtXLoydLqXI2Z63AKCJmSMwfy/HfsISusoXazjDi3Kdl/vMDz+S5+aCegGvgpxqPcAkfEuB/JM2xseJMksI+A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: argo
    type: kubernetes.io/dockerconfigjson

