apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo-events
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    k8s-gitops:
      owner: ACortesDev
      repository: k8s-gitops
      webhook:
        endpoint: /k8s-gitops
        port: "12000"
        method: POST
        url: http://webhook.172.19.0.3.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json