apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-teams
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "AppProject to define all Product Teams' permissions"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: https://74.220.19.36:6443
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: product-teams
  source:
    repoURL: https://github.com/ACortesDev/k8s-gitops
    targetRevision: HEAD
    path: product-team-A/gitops
  destination:
    server: https://74.220.19.36:6443
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
