apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-teams
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "AppProject to define all Product Teams' permissions"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: development
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-self-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ACortesDev/k8s-gitops
    targetRevision: HEAD
    path: platform-team/self-service/applications
  destination:
    name: development
    namespace: vela-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
