apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-a
spec:
  serviceAccountName: argoworkflows-argo-workflows-server
  entrypoint: main
  volumes:
  - name: regcred
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
    - name: main
      dag:
        tasks:
          - name: build
            templateRef:
              name: build-image
              template: build-kaniko-git
              clusterScope: true
            arguments:
              parameters:
              - name: repo_url
                value: git://github.com/ACortesDev/k8s-gitops
              - name: repo_ref
                value: refs/heads/main
              - name: repo_commit_id
                value: HEAD
              - name: container_image
                value: alvarocortes/acortes
              - name: container_tag
                value: "0.1"
              - name: dockerfile_path
                value: apps/app-A/Dockerfile
