apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-image
spec:
  serviceAccountName: argoworkflows-argo-workflows-server
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: repo_url
      - name: repo_ref
      - name: repo_commit_id
      - name: container_image
      - name: container_tag
      - name: dockerfile_path
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
      - --context={{inputs.parameters.repo_url}} # #{{inputs.parameters.repo_ref}}#{{inputs.parameters.repo_commit_id}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      - --dockerfile={{inputs.parameters.dockerfile_path}}
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker/
