apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
    - name: app-a
      type: backend-microservice
      properties:
        image: alvarocortes/acortes:1.0.0
        feature-toggles:
          feature-foo: "off"
          feature-bar: "off"
  
  policies:
    - name: cluster-policy
      type: env-binding
      properties:
        envs:
          - name: development
            placement:
              clusterSelector:
                name: civo-london
              namespaceSelector:
                name: development
  
  workflow:
    steps:
      - name: deploy
        type: deploy2env
        properties:
          policy: cluster-policy
          env: development
