apiVersion: cluster.civo.crossplane.io/v1alpha1
kind: CivoKubernetes
metadata: 
  name: civo-london
spec:
  name: civo-london
  pools:
    - id: "a-random-uuid"
      count: 1
      size: g3.k3s.small
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-config
